# Generated by Django 6.0.7 on 2026-08-26 18:04

from django.db import migrations, models


SUBJECT_TAGS = [
    'Science', 'Maths', 'English', 'Biology', 'Chemistry', 'Physics',
    'History', 'Geography', 'Modern Languages', 'Computing', 'Art', 'Music',
    'Drama', 'Design and Technology', 'Religious Studies', 'Physical Education',
    'Business Studies', 'Citizenship',
]


def seed_subject_tags(apps, schema_editor):
    SubjectTag = apps.get_model('lms_app', 'SubjectTag')
    SubjectTag.objects.bulk_create([SubjectTag(name=name) for name in SUBJECT_TAGS])


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_remove_roleapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='lms_app.subjecttag'),
        ),
        migrations.RunPython(seed_subject_tags, migrations.RunPython.noop),
    ]
